language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - pdd --file=/dev/null
  - mvn clean site -Psite --errors --batch-mode
  - mvn clean install -Pqulice --errors --batch-mode
install:
  - gem install pdd
  - gem install xcop
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
services:
    - mysql
    - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
before_install:
  - psql -c "CREATE EXTENSION pgcrypto;" -U postgres template1
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
jdk:
  - oraclejdk8
