language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - pdd --file=/dev/null
  - mvn clean site -Psite --errors --batch-mode
  - mvn clean install -Pqulice --errors --batch-mode
install:
  - gem install pdd
  - gem install xcop
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
services:
    - mysql
    - postgresql
before_install:
    - psql -c 'CREATE EXTENSION pgcrypto;' -U postgres template1
jdk:
  - oraclejdk8
